# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=200)),
                ('publication_type', models.CharField(choices=[('a', 'type a'), ('b', 'type b')], max_length=1)),
                ('campus', models.CharField(max_length=4)),
                ('campus_unit', models.CharField(max_length=200)),
                ('publishing_partner', models.CharField(max_length=200)),
                ('regents_owned', models.BooleanField()),
                ('url', models.URLField()),
                ('contact_email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('peer_reviewed', models.BooleanField()),
                ('active', models.BooleanField()),
                ('distributor', models.CharField(max_length=200)),
                ('issn', models.CharField(max_length=200)),
            ],
        ),
    ]
