# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-09 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(blank=True, help_text='name of the publication', max_length=200)),
                ('publishing_partner', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True, help_text='should this have date range?')),
                ('distributor', models.CharField(blank=True, help_text='books only', max_length=200)),
                ('issn', models.CharField(blank=True, help_text='journals only', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ManyToManyField(blank=True, to='publishing_projects.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='unit hosting program', max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishing_projects.PublishingProgram'),
        ),
        migrations.AddField(
            model_name='project',
            name='publication_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='publishing_projects.PublicationType'),
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ManyToManyField(blank=True, to='publishing_projects.Subject'),
        ),
    ]
