# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-27 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing_projects', '0002_auto_20200227_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='distributor',
            field=models.CharField(blank=True, help_text='books only', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='issn',
            field=models.CharField(blank=True, help_text='journals only', max_length=200),
        ),
    ]
